// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: placeholder.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1
`

// Placeholder so `sqlc generate` has a query to compile while the schema is empty (internal/db must exist and compile).
// Delete this file once the first real query file (internal/db/queries/<resource>.sql) exists.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
